version: '3.8'
services:
  redis_chat_db:
    image: redis:latest
    command: redis-server
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/data-config/:/usr/local/etc/redis/redis.conf

  chatapp_db:
    image: postgres:latest
    container_name: chat_app
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    restart: always
    volumes:
      - chat_app_database:/var/lib/postgresql/data/

  chatapp_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python -m manage migrate && 
      python -m manage collectstatic --noinput && 
      mkdir -p /certs &&
      touch certs/privkey.pem && 
      touch certs/fullchain.pem && 
      daphne -e ssl:8000:privateKey=certs/privkey.pem:certKey=certs/fullchain.pem config.asgi:application"
    image: chatapp:latest
    depends_on:
      - chatapp_db
      - redis_chat_db
    restart: on-failure
    ports:
      - "9045:8000"
    volumes:
      - /var/www/chat-app-data/media:/api/media
      - /etc/letsencrypt/live/chatapi.vitaliisili.com/privkey.pem:/api/certs/privkey.pem
      - /etc/letsencrypt/live/chatapi.vitaliisili.com/fullchain.pem:/api/certs/fullchain.pem

volumes:
  chat_app_database: