version: '3.8'
services:
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/data-config/:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'